### ISSUE TITLE
Can't extend beyond bottom safe area

### ISSUE THREAD

**Issue by DouglasHennrich** [gordontucker/FittedSheets#104]
I'm using version `2.1.5`

Can I extend to beyond bottom safe area? So it fill the bottom screen size

```swift
guard let viewController = YDMHomeBottomSheetViewController.initializeFromStoryboard()
			else {
				fatalError()
		}

		//
		viewController.viewModel = viewModel

		let options = SheetOptions(
			pullBarHeight: 24,
			presentingViewCornerRadius: 16,
			useFullScreenMode: true,
			useInlineMode: true
		)

		bottomSheet = SheetViewController(
			controller: viewController,
			sizes: [
				.percent(0.8),
				.percent(0.88)
			],
			options: options
		)

		bottomSheet.willMove(toParent: self)
		self.addChild(bottomSheet)
		view.addSubview(bottomSheet.view)
		bottomSheet.didMove(toParent: self)

		// Auto layout
		bottomSheet.view.translatesAutoresizingMaskIntoConstraints = false
		NSLayoutConstraint.activate([
				bottomSheet.view.topAnchor.constraint(equalTo: view.topAnchor),
				bottomSheet.view.bottomAnchor.constraint(equalTo: view.bottomAnchor),
				bottomSheet.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
				bottomSheet.view.trailingAnchor.constraint(equalTo: view.trailingAnchor)
		])

		// The size of the grip in the pull bar
		bottomSheet.gripSize = CGSize(width: 29, height: 3)

		// The color of the grip on the pull bar
		bottomSheet.gripColor = UIColor(
			red: 199/255,
			green: 199/255,
			blue: 204/255,
			alpha: 1
		)

		// Disable the dismiss on background tap functionality
		bottomSheet.dismissOnOverlayTap = false

		// Disable the ability to pull down to dismiss the modal
		bottomSheet.dismissOnPull = false

		// Change the overlay color
		bottomSheet.overlayColor = .clear

		//
		bottomSheet.allowGestureThroughOverlay = true

		//
		bottomSheet.allowPullingPastMinHeight = false

		// animate in
		bottomSheet.animateIn()
```
![Simulator Screen Shot - iPhone 11 Pro - 2020-09-29 at 14 32 05](https://user-images.githubusercontent.com/10107024/94595136-c7f88100-0260-11eb-92de-297560b3de38.png)

**Comment by gordontucker** [comment]
It isn't restricting any safe area at the bottom. Are you sure the view you are adding the sheet to actually extends to the bottom instead of only to the safe area?

**Comment by DouglasHennrich** [comment]
This is the view controller which are adding the sheet

![Captura de Tela 2020-09-29 às 14 48 11](https://user-images.githubusercontent.com/10107024/94596666-cfb92500-0262-11eb-8285-1526db0e65e5.png)

**Comment by DouglasHennrich** [comment]
BTW there's a "expand/collapse" event to listen?

**Comment by gordontucker** [comment]
It is definitely something set up wrong in one of your views. I added an example in the demo project that shows it working (click the navbar item "inline" then click the navbar item "safearea" to get to this example)

Here is what it looks like when presented (using your sheet settings to present)
![Simulator Screen Shot - iPhone 11 - 2020-09-29 at 11 55 24](https://user-images.githubusercontent.com/168661/94597572-fbc8ac00-024a-11eb-934c-bae164328475.png)

As far as "expand/collapse" you would want to use the `sizeChanged` closure property

**Comment by DouglasHennrich** [comment]
Thanks for `sizeChanged` :D

and yea.. it has a `safe bottom` constraint on my view controller (injected on sheet)... I just change it to superview and works :D Thanks
