### ISSUE TITLE
update size from the child viewcontroller

### ISSUE THREAD

**Issue by syrakozz** [gordontucker/FittedSheets#11]
hi 
how i can update size of the sheet  from the child viewcontroller

**Comment by gordontucker** [comment]
I will take a look at this. It should be doable, I just think I need to add a function to allow it.

**Comment by gordontucker** [comment]
In version 1.1.1 you can achieve this with one of two ways:

For a temporary resize, that will not stick when they drag the sheet
```
self.sheetViewController?.resize(to: .fixed(150))
```

For a permanent resize
```
self.sheetViewController?.setSizes([.fixed(150)])
```
