### ISSUE TITLE
Can't interact with background components on inline mode

### ISSUE THREAD

**Issue by Dhaval3110** [gordontucker/FittedSheets#110]
When I'm adding a sheet view controller as an inline mode not able to interact with backside views.
Just check the given attachment. not able to interact with four-button in back

` 
let controller = rbStoryboard.asset.instantiateViewController(withIdentifier: "AssetDetailsVC") as! AssetDetailsVC

        let options = SheetOptions(
            pullBarHeight: 24,
            presentingViewCornerRadius: 16,
            useFullScreenMode: true,
            useInlineMode: true
        )

        let sheetController = SheetViewController(controller: controller, sizes: [.percent(0.2), .intrinsic], options: options)
        sheetController.dismissOnOverlayTap = false
        sheetController.autoAdjustToKeyboard = true
        sheetController.dismissOnOverlayTap = false
        sheetController.dismissOnPull = false
        // Add child
        sheetController.willMove(toParent: self)
        self.addChild(sheetController)
        view.addSubview(sheetController.view)
        sheetController.didMove(toParent: self)

        sheetController.view.translatesAutoresizingMaskIntoConstraints = false
        NSLayoutConstraint.activate([
            sheetController.view.topAnchor.constraint(equalTo: view.topAnchor),
            sheetController.view.bottomAnchor.constraint(equalTo: view.bottomAnchor),
            sheetController.view.leadingAnchor.constraint(equalTo: view.leadingAnchor),
            sheetController.view.trailingAnchor.constraint(equalTo: view.trailingAnchor)
        ])

        // animate in
        sheetController.animateIn()`
![Simulator Screen Shot - iPhone 11 - 2020-10-15 at 11 40 14](https://user-images.githubusercontent.com/6889248/96083695-59135d00-0edb-11eb-975a-6fdc7c9a1b50.png)

**Comment by gordontucker** [comment]
You'll need to set `sheetController.allowGestureThroughOverlay = true` to be able to interact with things behind the sheet.
