### ISSUE TITLE
Something with pod versioning

### ISSUE THREAD

**Issue by antons81** [gordontucker/FittedSheets#117]
Hi, I've got version 1.4.6 from pod, but on the main page last version is 2.2.2. Could you please fix this?

**Comment by gordontucker** [comment]
Do you meet the minimum requirements for that version or are you targeting too old of an old version of iOS?

**Comment by antons81** [comment]
Ok,  you right, I've increased platform :ios, to '11.0' and it solved this issue

**Comment by gordontucker** [comment]
Glad to hear it!
