### ISSUE TITLE
Weird sweeping issue first time presenting SheetController

### ISSUE THREAD

**Issue by bryan-vh** [gordontucker/FittedSheets#118]
When I call present from my viewcontroller to show the SheetController, the dimmed background sweeps across the screen from left to right over the presenting view controller. It only does this when the SheetController is first presented but not after. Unsure as to what might be causing this issue, but wanted to ask if there's a property or something I'm missing that could be causing this.

I'm using this function to present from my original view controller but then display the content inside the current view controller.

```
public func present(from viewController: UIViewController) {
        let sheetOptions = SheetOptions(shrinkPresentingViewController: false)
        let sheetController = SheetViewController(controller: self, options: sheetOptions)
        sheetController.cornerRadius = 20
        sheetController.allowPullingPastMaxHeight = false
        viewController.present(sheetController, animated: true)
}
```

[Sheets Issue.mov.zip](https://github.com/gordontucker/FittedSheets/files/5575854/Sheets.Issue.mov.zip)

**Comment by gordontucker** [comment]
The only time I've seen things like this is when I'm doing UIView animations inside the viewDidLoad (or somewhere else that is trying to animate during the initial presentation of the controller).

**Comment by hipwelljo** [comment]
I have this same issue with a view controller whose height is determined by the height of a collection view. I update a height constraint constant to match its `contentSize.height`. I've attached a simple example project. I'm upgrading from version 1.4.5 where it didn't occur.
[Test.zip](https://github.com/gordontucker/FittedSheets/files/5766951/Test.zip)


https://user-images.githubusercontent.com/6282848/103583321-c6aca500-4e9c-11eb-9c84-29b23e0c2011.mov

**Comment by gordontucker** [comment]
Thank you for the sample. I'll get this fixed as soon as I can.

**Comment by gordontucker** [comment]
So I'm looking into it and it appears that changing the height that way in the viewDidLoad is the trigger for the bug. I haven't figured out how to prevent that problem yet, but moving the logic into viewWillAppear instead of viewDidLoad fixes the animation bug.

From the sample app, this no longer has the problem:
```
    override func viewDidLoad() {
        super.viewDidLoad()
        
        collectionView.contentInset = UIEdgeInsets(top: 0, left: 20, bottom: 0, right: 20)
        collectionView.register(SlideInAnimationBug118TagCell.self, forCellWithReuseIdentifier: "cell")
        
        let layout = collectionView.collectionViewLayout as! UICollectionViewFlowLayout
        layout.estimatedItemSize = CGSize(width: 150, height: 32)
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        //keep the height of the collection view equal to the height of its content size
        contentSizeObserverToken?.invalidate()
        contentSizeObserverToken = collectionView.observe(\UICollectionView.contentSize, options: [.new]) { [weak self] (object, change) in
            guard let selfie = self else { return }
            
            let newHeight = selfie.collectionView.contentSize.height
            if newHeight > 0 && newHeight != selfie.collectionViewHeightConstraint.constant {
                print(selfie.collectionView.contentSize.height)
                UIView.performWithoutAnimation {
                    selfie.collectionViewHeightConstraint.constant = newHeight
                }
            }
        }
    }
```

I'll continue to look into it, but this should give you a workaround until I figure that out.

**Comment by hipwelljo** [comment]
Confirmed thank you!

**Comment by muriginvlad** [comment]
As I understand it, the problem could not be solved? (

**Comment by gordontucker** [comment]
I just haven't had time to look into it. I'm sure it is solvable, just been too busy

**Comment by 2Grey** [comment]
You can use Dispatch for solving problem:

```swift
override func viewDidLoad() {
    super.viewDidLoad()
       
    DispatchQueue.main.async {
        self.recalculateHeight()
    }
}
```
