### ISSUE TITLE
[QUESTION] : how can I prevent intrinsic sized controller from being extended?

### ISSUE THREAD

**Issue by jerometonnelier** [gordontucker/FittedSheets#119]
Hi and tanks for this great library ;-)

I currently use it to show a controller as a card, but I'd like to prevent it from being stretched when the user drags up (i.e. : the max size being the intrinsic size). Is there a way to achieve this?

Thanks

**Comment by bryan-vh** [comment]
I think you can use the sheetController.allowPullingPastMaxHeight = false and that should disable stretching past the intrinsic content size.

**Comment by jerometonnelier** [comment]
Thanks @bryan-vh worked like a charm <3
