### ISSUE TITLE
How change width  Bottom Sheets? 

### ISSUE THREAD

**Issue by v-murygin** [gordontucker/FittedSheets#127]
Hello @gordontucker.

Please tell me how i can change the width  Bottom Sheets in your library?

**Example:**
<img height="300" src="https://user-images.githubusercontent.com/41015200/103168333-38547580-4843-11eb-8b06-b2c525a04dfa.jpeg " />   <img height="300" src="https://user-images.githubusercontent.com/41015200/103168335-38ed0c00-4843-11eb-8bf1-ded1adafc885.jpeg" />

**Comment by gordontucker** [comment]
That is currently not a supported feature.

**Comment by gordontucker** [comment]
The ability to set the width has been added in version 2.3.0

**Comment by muriginvlad** [comment]
Thx. As I understand , you added a fixed width on creation. 
I would like to know if there is a dynamic narrowing (animated) option when the height changes.

Below is an example, but it has minor bugs:
https://user-images.githubusercontent.com/41015200/103815180-05488800-5074-11eb-807c-c7c989537e68.mp4

**Comment by gordontucker** [comment]
There is not. I don't see myself adding that particular functionality into FittedSheets, at least not in any near term.

**Comment by stoletnaedine** [comment]
@gordontucker Hello!
Thnx for amazing library.
I'm using FittedSheets in my app and really need to dynamically change the width with a scroll.
Pls add the feature 🚀

**Comment by gordontucker** [comment]
I added a property to attempt this behavior. I haven't tested it a crazy amount, but hopefully it works for you good enough. It is in build 2.5.1.
