### ISSUE TITLE
Not dismiss on scroll to bottom

### ISSUE THREAD

**Issue by javigines** [gordontucker/FittedSheets#129]
Hi @gordontucker,

I had supposed that when I scroll to bottom the sheet it would dismiss itself and the child associated but it only hides them, and it causes that on any scroll over the screen the sheet appears again because it wasn't dismissed. 

I have checked the code in the panned function and it is commented the word dismiss but it doesn't dismiss the vc, it only hides it.
```

            case .ended:
                let velocity = (0.2 * gesture.velocity(in: self.view).y)
                var finalHeight = newHeight - offset - velocity
                if velocity > 500 {
                    // They swiped hard, always just close the sheet when they do
                    finalHeight = -1
                }
                
                let animationDuration = TimeInterval(abs(velocity*0.0002) + 0.2)
                
                guard finalHeight > 0 || !self.dismissOnPull else {
                    if self.options.useInlineMode {
                        self.attemptDismiss(animated: true, duration: animationDuration)
                    } else {
                        // Dismiss
                        UIView.animate(
                            withDuration: animationDuration,
                            delay: 0,
                            usingSpringWithDamping: self.options.transitionDampening,
                            initialSpringVelocity: self.options.transitionVelocity,
                            options: self.options.transitionAnimationOptions,
                            animations: {
                            self.contentViewController.view.transform = CGAffineTransform(translationX: 0, y: self.contentViewController.view.bounds.height)
                            self.view.backgroundColor = UIColor.clear
                            self.transition.setPresentor(percentComplete: 1)
                            self.overlayView.alpha = 0
                        }, completion: nil)
                    }
                    return
                }
```

I don't see any initial configuration or delegate where I received the actual heigh of the sheet if I have to dismiss it. So I'm a bit lost with how to solve this. If `shouldDismiss` were called I could return true to dismiss it, but in the panned ended case is not called.

I don't know if is a problem with the tableview I have inside the embedded VC or what.

Here you can view a video of the behaviour of the sheet.

https://user-images.githubusercontent.com/15628852/104110021-db8d9c00-52d3-11eb-8075-a78e69fd3f13.mov

I'm testing on iOS 14.3 as you can see in the video

**Comment by gordontucker** [comment]
I'll work on this. Thank you for reporting it.

**Comment by gordontucker** [comment]
The change that caused this has been reverted and it shouldn't be a problem anymore (as of 2.3.1)

**Comment by javigines** [comment]
Everything working again. Great work.
