### ISSUE TITLE
Allowing gestures below BottomSheet

### ISSUE THREAD

**Issue by stelpk** [gordontucker/FittedSheets#130]
Hello again,

I would like to ask you if it's possible to have access below the bottomSheet(to the controller presenting the sheet). So in my case the bottomSheet has height equal to 150 points and I want to allow tapping below it. I ran your demo but I couldn't find any sample containing the desired functionality. In addition, I attempted using the 'allowGestureThroughOverlay' option and settings the 'hasBlurBackground' into false without any positive result. Is it a proper way to enable this kind of functionality? Thank you in advance.

**Comment by stelpk** [comment]
Any update on that? Thank you in advance.

**Comment by gordontucker** [comment]
You'd need to run it as an "inline" sheet. Typically it is presented modally (that is how I wrote it to be used initially), but I added the inline version for people that wanted it to do what you are describing.

**Comment by gordontucker** [comment]
Make sure to update to the latest (2.3.2), I fixed a bug with inline presentations in that build.
