### ISSUE TITLE
How to handle a table view with dynamic number of items in sheet view controller

### ISSUE THREAD

**Issue by bryan-vh** [gordontucker/FittedSheets#136]
I have a view controller that contains a table view. Ideally, the table view will have a fixed number of fixed size rows so I could manually set the height by estimating the total size needed, but I would prefer it if the sheet view controller could determine the size of the table view from its content. Is there anything I need to do to make this work, because when I try to present my view controller in a sheet view controller without specifying a fixed size it doesn't show anything. However, when I present modally (like a normal presentation) I can see the table view and its content.

Thanks!

**Comment by gordontucker** [comment]
What you want to do is set a minimum height on the view (so it will initially render property), then set up a property observer on the table view's contentSize. Whenever that changes, set the fitted sheet's height to match (you may have to adjust based on safe areas, navigation bars, etc. Depends how your screens are set up. This should give you the effect you are looking for.

**Comment by bryan-vh** [comment]
@gordontucker thanks for the reply. Since my content in the table view is essentially static I decided to use the fixed size approach in the interim which works well enough since that content should rarely change. But this is good to know for the future! Thanks again!
