### ISSUE TITLE
Event callback as the sheet is being dragged

### ISSUE THREAD

**Issue by iqra-padela** [gordontucker/FittedSheets#137]
There is a completion callback when the sheet is dragged to a new position. However, is there is a callback where I continually get updates as the sheet is being dragged?

**Comment by gordontucker** [comment]
There is not currently. You might be able to use a property observer on the SheetViewController view's bounds to get what you need right now.

**Comment by bobysdev** [comment]
can I know about the call back ?
which is called when sheet is not the new position 
I need this and I could not find it

**Comment by sultan-arshi** [comment]
can I know about the call back ?
which is called when sheet is not the new position
I need this and I could not find it

**Comment by sultan-arshi** [comment]
```
 guard let sheetController = self.sheetViewController else { return }
        sheetController.sizeChanged = {[weak self] (controller, size, value) in
            // here to handle when size changed
        }
```
I used above code into child VC
