### ISSUE TITLE
where can I find just the asset for the gray line

### ISSUE THREAD

**Issue by 8secz-johndpope** [gordontucker/FittedSheets#138]
<img width="370" alt="Screen Shot 2021-03-04 at 12 50 25 am" src="https://user-images.githubusercontent.com/50567111/109817274-d884ab80-7c85-11eb-962e-fa0534a5107d.png">

there's no png used that I can see - is it a view manually crafted? how to inject into navigation title? just addsubview?

**Comment by 8secz-johndpope** [comment]
but where? it's not a xib is it?

**Comment by gordontucker** [comment]
Look for the properties `pullBarView` and `gripView` on the controller `SheetContentViewController`. No xibs or assets are being used in this project. Everything is programmatic.
