### ISSUE TITLE
is there a way for the Bottom Sheet to behave like the one on Apple Maps?

### ISSUE THREAD

**Issue by fealaure** [gordontucker/FittedSheets#139]
I'm trying to set the bottom sheet always visible and still let the user interact with the parent view like the Apple Maps or Stocks app.
Is there a way to achieve this behavior?

**Comment by gordontucker** [comment]
This should be possible for you to accomplish. Look at this `inline` demos. Present that way (instead of modally) and set the appropriate settings to disable dismissing the bottom sheet.
