### ISSUE TITLE
How to move table view cells?

### ISSUE THREAD

**Issue by Anton-Skidan** [gordontucker/FittedSheets#140]
Hello, I've created view controller with table view and want to move cells ( panGesture ) but logic in "panned" does not let me to do this. 
If I am using handleScrollView delegate and put there my table view it let me moving cells from down to up , but I am sure that is a wrong way. Also I still can't move cells from up to down.
I use vc with allowPullingPastMaxHeight = false.
So,  How to move table view cells?
Thanks

**Comment by gordontucker** [comment]
I'm not sure how to answer this without a more specifics (a working demo would be best) on how you've implemented things.

All handleScrollView is doing is telling your scrollview to require the fitted sheet's pan gesture to fail before beginning. You may have to change how that works and implement it yourself for your specific scenario.

**Comment by Anton-Skidan** [comment]
Hello, I've found the solution
shouldRecognizePanGestureWithUIControls = false
