### ISSUE TITLE
FittedSheets (not modal) + TableView + leadingSwipeActionsConfigurationForRowAt

### ISSUE THREAD

**Issue by abbana** [gordontucker/FittedSheets#143]
Hi,

thanks for the wonderful pod.

I have a tableview in one of my FittedSheets , the tableview works like a charm.

Now I want to allow swipe right/left on the cell, so I have just used the leadingSwipeActionsConfigurationForRowAt and trailingSwipeActionsConfigurationForRowAt which I am using in a "classic" VC with tableview.

I think there is a gesture recognizer conflict as it almost impossible to fire leadingSwipeActionsConfigurationForRowAt and trailingSwipeActionsConfigurationForRowAt within a tableview in FittedSheets.

Have you tested this user case? How can I get to work?

**Comment by gordontucker** [comment]
This isn't something I've tested, so I'm not sure why it isn't working. Look into how the pan gestures are interaction and likely one or the other needs to wait for failure.

**Comment by abbana** [comment]
I do agree,

where in the code I can stop gestures for FittedSheets so I can check if then leadingSwipeActionsConfigurationForRowAt  and take from there to assign the right priority to each of the two?

**Comment by abbana** [comment]
Solved.

returned false in
`public func gestureRecognizerShouldBegin(_ gestureRecognizer: UIGestureRecognizer) -> Bool {`

when 
```
leadingSwipeActionsConfigurationForRowAt
trailingSwipeActionsConfigurationForRowAt
willBeginEditingRowAt
```

cancelled by
`didEndEditingRowAt`

**Comment by Elzawawy** [comment]
@abbana Hello there, 
I am facing a similar issue to yours, and was wondering if you can elaborate more information on your fix. I understand you are saying there is a conflict between the gesture recognizers set by Fitted Sheets and by the swiping gestures for UITableView ones. However, I cannot quite grasp how did you solve that conflict. Thank you!
