### ISSUE TITLE
Sheet-like Window Sliding

### ISSUE THREAD

**Issue by 8secz-johndpope** [gordontucker/FittedSheets#144]
I have a basic  master list vc / detail view controller in a navigation controller.
I want to show sheets on the list vc / but then push say a user icon in the sheets and and then push the the detail (along with the sheets) to show new vc. (It's like TikTok clicking a user in comments.) 

https://stackoverflow.com/questions/574680/core-animation-sheet-like-window-sliding
https://www.raywenderlich.com/1005187-how-to-create-your-own-slide-out-panel-navigation

It seems straightforward to add the sheets to the navigationcontroller main view - but needs animating. 
https://stackoverflow.com/questions/19257999/add-child-view-controller-to-uinavigationcontroller/22646474

**Comment by gordontucker** [comment]
If you want to do that, don't present modally. Instead present inline (it will show as a subview of whatever view you add it to). That way it is tied to the view it is in instead presenting over the top of everything.

**Comment by 8secz-johndpope** [comment]
thanks Gordon
