### ISSUE TITLE
Compatibility error with MercadoPago

### ISSUE THREAD

**Issue by DaveGallegos** [gordontucker/FittedSheets#149]
The library has problems when used together with the MercadoPago library (pod 'MercadoPagoSDK', '~> 4.32'), it shows different errors when trying to install the pods, this problem is solved with this:

 pre_install do |installer|
        # workaround for https://github.com/CocoaPods/CocoaPods/issues/3289
        Pod::Installer::Xcode::TargetValidator.send(:define_method, :verify_no_static_framework_transitive_dependencies) {}
  end

When compiling, several lines of code start to fail in the library of 
pod 'FittedSheets'

**Comment by gordontucker** [comment]
I'm not sure why their code isn't working or why the workaround for their broken code is causing this pod to break. Sorry I can't help with this issue.
