### ISSUE TITLE
Problems with Sheet as UINavigationController on non "X" iPhone series of devices

### ISSUE THREAD

**Issue by alfonsotesauro** [gordontucker/FittedSheets#15]
I am using this project extensively in my app. I have now an issue. In a SheetViewController created using a UINavigationController, I have a UITextView. Before I edit the text in the UITextView, everything works as expected :

<img width="598" alt="screenshot 2018-12-12 at 18 55 42" src="https://user-images.githubusercontent.com/12210731/49889212-39bfca80-fe41-11e8-9ddf-6a4d94c136cc.png">

but after I edit the text in the textview, and after I call self.view.endEditing(true) the navigation bar of the View Controller shifts some space from top, as you can see in this screenshot:

<img width="598" alt="screenshot 2018-12-12 at 18 56 15" src="https://user-images.githubusercontent.com/12210731/49889318-7f7c9300-fe41-11e8-8e15-96dfc2860497.png">

If I navigate back to the previous view controller, the navigation bar stays shifted from the top until the user closes the sheet.
Another strange thing is that this misbehaviour does not appear in the "X" series of devices. If I launch the simulator set to "iPhone X" the navigation bar works perfectly.

Thanks a lot for any help,

Alfonso

**Comment by alfonsotesauro** [comment]
I have further inspected the behaviour, and it appears that it happens because I have instantiated my SheetViewControllers with only the fullscreen size: "sizes: [.fullScreen]". If I use the values contained in your example project, everything works, but unfortunately it is not desirable for me to set other sizes. Is there any possible solution ? thanks again.

**Comment by gordontucker** [comment]
I'll take a look. Thanks for reporting the issue.

**Comment by gordontucker** [comment]
This should be fixed in 1.1.3
Let me know if there are any other issues.
