### ISSUE TITLE
Fullscreen robs UI of all gestures after dismissal

### ISSUE THREAD

**Issue by ghost** [gordontucker/FittedSheets#151]
STR: 

- Add a button to a screen 
- add a selector that triggers this code: 

```
let controller = UIHostingController(
            rootView:
                TodoView(
                    viewModel: TodoViewModel()
                )
        )

        let options = SheetOptions(
            shrinkPresentingViewController: false,
            useInlineMode: true
        )

        let sheetController = SheetViewController(
            controller: controller,
            sizes: [.percent(0.34), .fullscreen],
            options: options
        )

        self.present(sheetController, animated: true, completion: nil)
```

Then pull up to go fullscreen and pull down to dismiss. The button that presented the sheet is no longer tappable. :( the entire UI becomes frozen.

**Comment by madeofmoney** [comment]
Basically the problem is your PULL down to dismiss gesture doesn't actually call **dismissViewController** on the presenting controller so it thinks the UI is still there but it's not.

**Comment by madeofmoney** [comment]
If anyone has this issue and is reading this - here is a nasty hot fix. 
```
sheetController.didDismiss = { _ in
            self.dismiss(animated: false, completion: nil)
        }
```
Thanks for the lib @gordontucker 👍 lmk if you resolve this!

**Comment by laohanme** [comment]
Same issue here

**Comment by gordontucker** [comment]
It appears you are attempting to use inline mode (where you should be adding as a subview) at the same time as `self.present()` (which is how you present modals). Try removing the `.useInlineMode` or presenting as shown in the inline mode examples
