### ISSUE TITLE
Allow "rubber band" when pulling beyond max height

### ISSUE THREAD

**Issue by llinardos** [gordontucker/FittedSheets#154]
Allow this kind of native "rubber band" effect:

https://user-images.githubusercontent.com/4202511/128634385-5fd04c5a-a41a-4729-a755-e332aa11724e.mp4
https://user-images.githubusercontent.com/4202511/128634378-b4a2dfd7-d74d-49eb-b20b-f0dcede52761.mp4

**Comment by gordontucker** [comment]
This functionality was merged into the latest release.
