### ISSUE TITLE
Tap to open

### ISSUE THREAD

**Issue by Xedart** [gordontucker/FittedSheets#156]
I want to be able not to only open the sheet by pulling, but also by tapping on it. How can I achieve it?

**Comment by gordontucker** [comment]
There is a demo in the repository with an example of how to use buttons to resize the sheet. It is the "Resize buttons" demo.

Or are you wanting to tap on the sheet's handle and have that resize it? If so, you can find that control by using `sheetViewController.contentViewController.pullBarView` (or `gripView`) and adding a gesture recognizer to that and doing the same behavior the resize demo is doing from there.
