### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by rastaman111** [gordontucker/FittedSheets#157]
Hey!
Example:
I have 5 buttons on the screen and clicking on it opens a detailed screen for everyone.

If I click on everything, then 5 detailed screens will open, but when I press the button, the previous one crawled away and a new one appeared

![IMG_9458](https://user-images.githubusercontent.com/15727518/129867445-ff61dc39-d1e6-4c9a-bbc5-615492b55114.PNG)

**Comment by gordontucker** [comment]
I'm not completely clear on what you are doing.
