### ISSUE TITLE
fitted Sheet above bottom tabbar item

### ISSUE THREAD

**Issue by DharaniDevApp** [gordontucker/FittedSheets#163]
<img width="209" alt="tabbar-item" src="https://user-images.githubusercontent.com/81207720/131715806-6288cd35-3cb7-4f2d-8992-aa11838e7539.png">

How to open fitted sheet above tabbar items.

**Comment by gordontucker** [comment]
You should look at the "Subview/Inline Sheet Demos" in the demo app. They are the example to show how to do this.
