### ISSUE TITLE
Intrinsic Height not updating for Scrollview 

### ISSUE THREAD

**Issue by ankitagarwal007** [gordontucker/FittedSheets#168]
If the view controller has a  Scrollview and its content size changes after viewdidload, say stack view has multiple views and we show hide views on user actions, then the bottom sheet height doesn't change, and if sometimes it changes to wrong height. Tried calling updatePreferredHeight.

**Comment by fukemy** [comment]
how did u solved this? I have tableviewcontroller too

**Comment by chetan-duke** [comment]
Any luck on this?

**Comment by chetan-duke** [comment]
Any luck on this?
