### ISSUE TITLE
Throw fatal error if sheet size .percent is > 100%

### ISSUE THREAD

**Issue by paulsUsername** [gordontucker/FittedSheets#177]
I made a silly mistake and could figure it for about an hour of passing .percent(60) to the sheet size. Got me thinking that have a .percent value > then 100 doesn't make sense (or at the very least I couldn't think of case for it).

A feature I would recommend is throwing a fatal if sheet size percent is > than .percent(1.0)

**Comment by gordontucker** [comment]
Definitely not throwing a fatal. I will add a debug message when someone sets the value above 1.0 though to make something like this easier to figure out. Thank you for the suggestion
