### ISSUE TITLE
handleScrollView not working when present childview(have tableview) with navigation

### ISSUE THREAD

**Issue by fukemy** [gordontucker/FittedSheets#18]
Hi.
I am trying to present navigationVC(root: myVC), inside myVC class i have tableview
I have set handleScrollView inside viewdidload of myVC but it not working, can you check this?

Thanks

**Comment by fukemy** [comment]
here is my code:
```
let sheetController = SheetViewController(controller: UINavigationController(rootViewController: myVC), sizes: [.fixed(500), .fullScreen])
        sheetController.blurBottomSafeArea = true
        sheetController.adjustForBottomSafeArea = true
```

**Comment by gordontucker** [comment]
Is your `myVC` getting loaded before you have added it to the sheetViewController? That is the only thing I can think that would prevent it from working.
If that is the case, maybe move the handleScrollView to the viewWillAppear and have it only load there the first time?

**Comment by gordontucker** [comment]
Hmm. I haven't tried it with UITableViewControllers (I find them very unhelpful and restrictive), so it must be something around that. I'll try to take a look sometime.
