### ISSUE TITLE
How to remove rounded corners when apply .fullscreen size

### ISSUE THREAD

**Issue by dm-katsubo** [gordontucker/FittedSheets#183]
In my case for devices without notch
<img width="451" alt="Снимок экрана 2022-06-22 в 14 53 30" src="https://user-images.githubusercontent.com/2629505/175023070-31e247a8-ff15-4514-9300-07d691420835.png">

Thanks!

**Comment by harish-suthar** [comment]
Try below code:

```swift
self.sheetViewController?.cornerCurve = .continuous
self.sheetViewController?.cornerRadius = 0
```
