### ISSUE TITLE
Tag a new release?

### ISSUE THREAD

**Issue by stevelandeyasana** [gordontucker/FittedSheets#184]
My app was affected by #118, which has since been fixed, but no release has been made since then. Would you mind tagging 2.4.3 so I can make my Cartfile nice again? Thanks! :-)

**Comment by rgal75** [comment]
We would also appreciate a release with #118 fixed.
Thanks in advance!

**Comment by gordontucker** [comment]
New version is 2.5.0 and should have the fix for 118. Sorry for the delay on getting this merged and tagged.
