### ISSUE TITLE
Is there any way to track the position of the SheetView ?

### ISSUE THREAD

**Issue by sultan-arshi** [gordontucker/FittedSheets#187]
I want to show and hide the some view on the basis of the size of the sheet
view is half opened and fully dragged, or the sheet is dragged to new position 
so, In short I want to know when the position of the sheet changes

**Comment by asar1** [comment]
Any update on that?
I'm stuck at this too....

**Comment by sultan-arshi** [comment]
```
guard let sheetController = self.sheetViewController else { return }
        sheetController.sizeChanged = {[weak self] (controller, size, value) in
            // here to handle when size changed
        }
```


I used above code into child VC
