### ISSUE TITLE
Make it always visible with a minimum height instead of dismissing it away

### ISSUE THREAD

**Issue by sasquatchgit** [gordontucker/FittedSheets#19]
Would it be possible to make the bottom sheet always visible (like Uber) instead of making it disappear on swiping down?

**Comment by gordontucker** [comment]
Not how it is currently written (as a modally presented view controller). That would require it written to be added as a subview instead, which is a pretty decent change in behavior. I'm not opposed to implementing that (or getting a pull request that adds that functionality as long as it doesn't break existing functionality), just don't have the time currently to do it myself

**Comment by AlexisLeon** [comment]
+1

**Comment by nizzam** [comment]
this idea is awesome.

**Comment by nativ18** [comment]
This is a great enhancement

**Comment by ramesh09ios** [comment]
Can you help me how can we achieve make it always visible.

**Comment by gordontucker** [comment]
This is implemented in 2.0.0. Look at the `inline` demo for examples on how to achieve this result.
