### ISSUE TITLE
For fullscreen mode is there any way to remove the top spacing between the pull bar and screen top area for devices with a notch?

### ISSUE THREAD

**Issue by harish-suthar** [gordontucker/FittedSheets#190]
For fullscreen mode is there any way to remove the top spacing between the pull bar and screen top area for devices with a notch?

See screenshot below for reference.

![Simulator Screen Shot - iPhone 13 mini - 2022-12-29 at 15 40 48](https://user-images.githubusercontent.com/91060750/209936720-7510c808-3067-496c-ae0c-e085b255854f.png)

**Comment by nunojfg** [comment]
extension UIViewController {
    var topBarHeight: CGFloat {
        var top = self.navigationController?.navigationBar.frame.height ?? 0.0
        if #available(iOS 13.0, *) {
            top += UIApplication.shared.windows.first?.windowScene?.statusBarManager?.statusBarFrame.height ?? 0
        } else {
            top += UIApplication.shared.statusBarFrame.height
        }
        return top
    }
}

sheetController.minimumSpaceAbovePullBar = presentingViewController.topBarHeight

**Comment by harish-suthar** [comment]
@nunojfg This is not working for it instead increases the above space, what I want to do is make it full screen without any space above.
