### ISSUE TITLE
smoothly motion

### ISSUE THREAD

**Issue by mahmoudshurrabkryptonic** [gordontucker/FittedSheets#192]
Hello,

I want to ask if i can able sheet to be moving smoothly without specific sizes, for example i want it to be first 300 height and then move smoothly to another height without jumping.

so please if it is valid please help me on that.

thanks

**Comment by mahmoudshurrabkryptonic** [comment]
Any help here?

**Comment by gordontucker** [comment]
I probably won't be implementing this specific use case, sorry.
