### ISSUE TITLE
Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by doxuto** [gordontucker/FittedSheets#203]
I face errors on Xcode 15 beta. Can you update repos?

![Screenshot 2023-06-13 at 15 24 01](https://github.com/gordontucker/FittedSheets/assets/6085631/982cab45-b6d6-40f1-8ec2-5138245ba4f9)

**Comment by aivatradev** [comment]
Same here, Xcode 14.3.1 and Xcode 15.0 Beta 1

**Comment by andreymosin** [comment]
Any ETA on merge please? @gordontucker

**Comment by gordontucker** [comment]
Fixing now. Sorry for the delay.

**Comment by AndrewSB** [comment]
released in 2.6.0
