### ISSUE TITLE
fixed height

### ISSUE THREAD

**Issue by AdieOlami** [gordontucker/FittedSheets#21]
is it possible to lock the FittedSheet when it slides open? so users can not dismiss the sheet

**Comment by gordontucker** [comment]
Not currently

**Comment by davcpas1234** [comment]
I am working on a PR to introduce this functionality, I should be able to share this soon.

**Comment by jordanhbuiltbyhq** [comment]
Would love to see this! Any updates @davcpas1234?

**Comment by davcpas1234** [comment]
@jordanbuiltbyhq I've got a release candidate ready for this, just got to find some time to test it. Should be within the next week

**Comment by davcpas1234** [comment]
@jordanhbuiltbyhq see above 👍
