### ISSUE TITLE
Xcode 15 - Stored properties cannot be marked unavailable with '@available'

### ISSUE THREAD

**Issue by dhvl1729** [gordontucker/FittedSheets#213]
![Screenshot 2023-09-24 at 12 47 10](https://github.com/gordontucker/FittedSheets/assets/34210710/9357fd21-260a-4310-af73-bc1e53cb7df4)

**Comment by thet-pi** [comment]
Duplicate @ https://github.com/gordontucker/FittedSheets/issues/214
