### ISSUE TITLE
Xcode 15 Stored properties cannot be marked unavailable with '@available' 

### ISSUE THREAD

**Issue by FaizUlHassan123** [gordontucker/FittedSheets#214]
![Screenshot 2023-09-25 at 12 43 46 PM](https://github.com/gordontucker/FittedSheets/assets/37914870/880fc636-fe7f-47e6-aea4-79a25c18f293)

**Comment by dheroying** [comment]
Same issue for me. How did you solve this?

**Comment by maximality** [comment]
Updating library to latest 2.6.1 version solved this one for me

**Comment by AndrewSB** [comment]
yeah, update to the latest release
