### ISSUE TITLE
Xcode 15 issues "Stored properties cannot be marked unavailable with '@available'"

### ISSUE THREAD

**Issue by Angkur03** [gordontucker/FittedSheets#215]
<img width="943" alt="Screenshot 2023-09-29 at 11 19 15 AM" src="https://github.com/gordontucker/FittedSheets/assets/74536923/5991c652-215a-4219-bf4d-384e023c450a">

**Comment by JuiceJW** [comment]
@Angkur03  Updating to the latest version of FittedSheets 2.6.1 fixes this problem. Alternatively you can fork the version you are using and fix the issue by returning the value.

E.g.
`public var gripSize: CGSize { return .zero }`

**Comment by Rohijulislam** [comment]
"To resolve the issue, simply update the 'FittedSheets'. If you wish to update only 'FittedSheets' without affecting other dependencies in the pod, use the following command in the terminal:

`pod update FittedSheets`

This command will fetch and install the latest version of 'FittedSheets,' which is currently version 2.6.1.

**Comment by andrey-grach** [comment]
Am I the only one with this problem?
```
[!] CocoaPods could not find compatible versions for pod "FittedSheets":
  In Podfile:
    FittedSheets (~> 4.6)

None of your spec sources contain a spec satisfying the dependency: `FittedSheets (~> 4.6)`.

```

**Comment by andrey-grach** [comment]
Am I the only one with this problem? 

```
[!] CocoaPods could not find compatible versions for pod "FittedSheets":
  In Podfile:
    FittedSheets (~> 2.6)

None of your spec sources contain a spec satisfying the dependency: `FittedSheets (~> 2.6)`.
```
