### ISSUE TITLE
Why is the sheetPoint() method not public?

### ISSUE THREAD

**Issue by AS2422** [gordontucker/FittedSheets#217]
I'm trying to implement closing the SheetViewController when clicking outside of it (clicking on the background). In this case, I use Inline presentation.
If the sheetPoint(inside point: CGPoint, with event: UIEvent?) -> Bool method were public, I could easily do it like this:
1. attach UITapGestureRecognizer to the view of the parent class
2. specify the selector in the tapgestor:
```
@objc func handleTap(_ sender: UITapGestureRecognizer) {
         if sender.state == .ended {
             let location = sender.location(in: nil)

             if !sheetController!.sheetPoint(inside: location, with: nil) {
                 sheetController?.animateOut()
             }
         }
     }
```

But instead I will have to come up with a more complex and inelegant solution.

I really don't understand why this method is not marked as public, because it is not used anywhere inside the library.

**Comment by aybarska** [comment]
did you tried using this ? 
```
// Disable the dismiss on background tap functionality
sheetController.dismissOnOverlayTap = false
```

**Comment by AndrewSB** [comment]
yeah we handle that kind of tap elsewhere to dismiss functionality internally within the library, let us know if that option doesn't work for you
