### ISSUE TITLE
Navigationcontroller cause weird behaviour

### ISSUE THREAD

**Issue by Berk-Kaya** [gordontucker/FittedSheets#24]
I have a ViewController which embedded in NavigationController. When I use sheetviewcontroller and touch the textfield then close keyboard the content weirdly jumps and goes back. 

        guard let controller = UIStoryboard.Authentication.instantiateInitialViewController() as? AuthenticationViewController else { return }
        let sheetController = SheetViewController(controller: controller, sizes: [.fixed(520)])
        sheetController.blurBottomSafeArea = true
        sheetController.extendBackgroundBehindHandle = true
        self.present(sheetController, animated: false, completion: nil)

This is how I call sheetviewcontroller from my navigationcontroller.  (Everything goes back to normal when I remove the navigationcontroller)

**Comment by gordontucker** [comment]
This should work better now (especially if you aren't trying to use intrinsic heights), but the keyboard + navigation stuff still isn't perfect if you navigate while the keyboard is present. I'd recommend dismissing the keyboard before navigating when using FittedSheets.
