### ISSUE TITLE
'internal(set)' modifier is redundant for an internal property

### ISSUE THREAD

**Issue by hipwelljo** [gordontucker/FittedSheets#28]
Xcode 10.2 shows a warning `'internal(set)' modifier is redundant for an internal property` in Yalta.swift line 266, `internal(set) var constraints = [NSLayoutConstraint]()`

**Comment by gordontucker** [comment]
I haven't converted to Xcode 10.2 yet. I will get this fixed when I do. Thanks for reporting it to me.

**Comment by gordontucker** [comment]
This has been fixed in 1.4.1
