### ISSUE TITLE
Customizable settings aren't working

### ISSUE THREAD

**Issue by juliusbtesh** [gordontucker/FittedSheets#31]
None of the customizable options seem to be working and the handle background is always transparent.

I am using the latest version of Xcode and tried on simulator and on physical device.

Any ideas what is going on here?

Also I noticed a strange animation happening with my text when expanding the sheet to full screen. The text decides to grow in size in a random spot on the sheet and then disappear... Whats up with that?

**Comment by gordontucker** [comment]
Have you tried running the examples and seeing what is different between your integrations and the examples?

**Comment by gordontucker** [comment]
This should work better in 2.0.0. Try it with that and if it doesn't work, open a new ticket
