### ISSUE TITLE
SheetViewController  UI decomposes when keyboard hides

### ISSUE THREAD

**Issue by designkros** [gordontucker/FittedSheets#36]
I have a UITextView inside the SheetViewController. When the UITextField resigns first responder and the software keyboard hides, the SheetViewController decomposes (video enclosed).

containerView.setNeedsLayout() on keyboardWillHide helps.

![FE7C0546-C399-4045-B503-A6FA81838B71](https://user-images.githubusercontent.com/4900672/56944906-7ad12680-6b25-11e9-8828-6081d68ce427.gif)

**Comment by gordontucker** [comment]
Fixed in 2.0.0
