### ISSUE TITLE
UIControls not working properly

### ISSUE THREAD

**Issue by danielhogl** [gordontucker/FittedSheets#37]
As I tried to use a UISlider in an FittedSheet, I noticed that the behaviour is broken. I guess it is related to the panGestureRecognizer of the SheetViewController. I found out that UIButton is already excluded from `shouldReceive touch`, because there were some problems, see:

`public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldReceive touch: UITouch) -> Bool {
       guard let view = touch.view else { return true }
        // Allowing gesture recognition on a button seems to prevent it's events from firing properly sometimes
        return !(view is UIButton)
    }`

Can we extend this from UIButton to UIControl, so that it works for all kind of controls?

**Comment by gordontucker** [comment]
This is implemented in 1.4.2
