### ISSUE TITLE
Conversion to Swift 5 is available

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [gordontucker/FittedSheets#43]
Xcode 10.2.1 is warning Conversion to Swift 5 is available for FittedSheets installed via CocoaPods. Funky because it is already Swift 5. If I let it run the conversion it'll say no source changes necessary, click update to change your target's build settings to use the latest Swift syntax. Clicking Update I see that changed `SWIFT_VERSION = 5;` to `SWIFT_VERSION = 5.0;` lol

**Comment by gordontucker** [comment]
I _think_ I've got this fixed.
