### ISSUE TITLE
[Feature Request] Extra pull up animation for fixed size views

### ISSUE THREAD

**Issue by haidarcorp** [gordontucker/FittedSheets#48]
If you check how facebook uses its similar implementation to this, what they do is they allow users to pull the sheet much higher than the fixed size, and then when the user releases it falls back into place.

It would make the sheet feel a lot more professional and juicy as opposed to how it behaves now when they try pulling it up (doesn't move at all).

Other than that, this is the best bottom sheet out there :)

**Comment by gordontucker** [comment]
This is implemented in 2.0.0 (optionally through a property)
