### ISSUE TITLE
Not always using intrinsic content size of view controller view

### ISSUE THREAD

**Issue by hipwelljo** [gordontucker/FittedSheets#51]
I'm attempting to determine why my sheet is always a fixed height rather than using the view controller's view's content size when it appears initially.
`let sheetController = SheetViewController(controller: mapOptions)`

I have constraints configured top to bottom and it appears the intrinsic content size is correct because when I log this the required height is 352 but the sheet is still only allowing my view to have a height of 276.

```
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        print(view.systemLayoutSizeFitting(CGSize(width: view.bounds.width, height: 0), withHorizontalFittingPriority: .required, verticalFittingPriority: .defaultLow))
        print(view.bounds)
    }
```

That prints:
```
(414.0, 352.6666666666667)
(0.0, 0.0, 414.0, 276.0)
```

Any ideas?

**Comment by simdani** [comment]
Have you figured out something? :)

**Comment by hipwelljo** [comment]
I haven't. It works for other view controller views like a simple box subview with a fixed height, but not this one with a more complex view hierarchy for some reason.

**Comment by hipwelljo** [comment]
I'm able to reproduce this by putting a label at the top then a stack view underneath it that contains a few buttons. The label is constrained to the safe area top, stack view has vertical spacing to label, and stack view is constrained to safe area bottom, so all vertical constraints are in place. The result is only the buttons are visible, if you expand its height then the label appears. Here's the storyboard I used to reproduce this, just replace that in the demo app: 
[SelfSizingExample.storyboard.zip](https://github.com/gordontucker/FittedSheets/files/3789704/SelfSizingExample.storyboard.zip)

If you add this into `viewDidAppear` in `IntrinsicExampleViewController` you can see it should have a higher height:

```
print(view.systemLayoutSizeFitting(CGSize(width: view.bounds.width, height: 0), withHorizontalFittingPriority: .required, verticalFittingPriority: .defaultLow))
print(view.bounds.size)
```
prints:
```
(414.0, 276.3333333333333)
(414.0, 256.0)
```

![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-30 at 09 12 39](https://user-images.githubusercontent.com/6282848/67871105-74802f00-faf5-11e9-9024-208f677902e7.png)
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-30 at 09 12 41](https://user-images.githubusercontent.com/6282848/67871093-70eca800-faf5-11e9-8001-7126560e2fc9.png)

**Comment by gordontucker** [comment]
This is fixed by adding a new `.intrensic` size explicitly. You can control if you want it intrinsically sized or explicitly sized now in 2.0.0.
