### ISSUE TITLE
Delegate on fullscreen

### ISSUE THREAD

**Issue by syd-srirak** [gordontucker/FittedSheets#52]
Hi, any idea how we could hook onto a callback if the sheet view has been expanded to full screen? Could be worth having a delegate available that sends back the current size of the container after the scroll has completed

**Comment by beingbarath** [comment]
Even I m facing issue with this. There is no callback on the different sizes of the Fitted Sheets.

**Comment by gordontucker** [comment]
This has been added for the 2.0.0 release. Look for the `sizeChanged: (SheetViewController, SheetSize, CGFloat)` property
