### ISSUE TITLE
Ability to change background color of containerView's base

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [gordontucker/FittedSheets#57]
I noticed when the keyboard appears the sheet is pushed up and an underlying view is shown below the keyboard that is always white. In our app we have a dark interface and the dark keyboard style looks bad on top of a white background.

This is set in `setUpContainerView()`: `subview.base.backgroundColor = UIColor.white`

It'd be great to be able to change that color. Thanks!

This is how it appears:
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-26 at 15 29 13](https://user-images.githubusercontent.com/15804476/71492510-f2f70580-27f4-11ea-8cb7-39942a209b32.png)

This is how I'd like it appear:
![Simulator Screen Shot - iPhone 11 Pro Max - 2019-12-26 at 15 25 59](https://user-images.githubusercontent.com/15804476/71492498-d65acd80-27f4-11ea-8051-62a806cc09ac.png)

**Comment by gordontucker** [comment]
Fixed in 2.0.0
