### ISSUE TITLE
Add some bounce to the presentation animation

### ISSUE THREAD

**Issue by hipwelljo** [gordontucker/FittedSheets#6]
Thanks for open sourcing this library! It looks quite promising. I would like to request the presentation animation be given a bit of a bounce, similar to the Facebook implementation, to add some polish. :)

**Comment by gordontucker** [comment]
I would also like to add some polish to the app. I haven't had a ton of time to add it recently, but I plan to add some functionality like you mentioned.

**Comment by mgrider** [comment]
It looks to me like the presentation animation is always a "fly in" style animation..? I tried changing the presentation style on the view controller I'm presenting, and that had no effect. Would be great to be able to configure the presenting animation. Looks like this already happens in a `SheetTransition` class, so it would be great to be able to specify our own, or just have some different options there. (My ideal would be to present upward from the bottom of the screen, like the "Cover Vertical" transition style.)

**Comment by mgrider** [comment]
I don't know what I changed in my implementation, but my presentation animation is no longer fly-in (somehow). I did make a bunch of changes to the screen I'm presenting. (So my previous comment is probably useless.)
