### ISSUE TITLE
Objective C support

### ISSUE THREAD

**Issue by alexanderludvigs** [gordontucker/FittedSheets#62]
Hi, I am trying to call `public convenience init(controller: UIViewController, sizes: [SheetSize] = [])`
from objective c view controller and it seems that "@objc" is needed at the beginning of this convenience init maybe more.

I have added `#import <mobilebank-Swift.h>` to my .m file and `@import FittedSheets;` to my .h file, I can do `SheetViewController *svc = [[SheetViewController alloc] init];` but not `SheetViewController *svc = [[SheetViewController alloc] initWithController.. ];`

Please help

**Comment by gordontucker** [comment]
Objective-C is not supported. I haven't used it in years and don't want to have to maintain for it. Sorry. Maybe you could fork and make an objective-c compatible version for yourself?
