### ISSUE TITLE
overlayColor is inaccessible due to internal protection level

### ISSUE THREAD

**Issue by hipwelljo** [gordontucker/FittedSheets#7]
The following code produces a build time error because overlayColor is not declared public, so it is not settable when I've installed it via CocoaPods.

```
let sheetController = SheetViewController(controller: viewController)
sheetController.overlayColor = .aqua
```

EDIT: Looks like this was already addressed, but installing the latest (1.0.0) from CocoaPods I still see it's not public.

**Comment by gordontucker** [comment]
Oops, looks like I need to push a new version. Thanks for calling this out.

**Comment by gordontucker** [comment]
Yeah, I tried to get it in yesterday but ran out of time. I am going to get it updated by tonight.

**Comment by gordontucker** [comment]
1.1.1 is live and you can change overlayColor. Sorry for the delay :)

**Comment by hipwelljo** [comment]
Thanks @gordontucker! I've updated but I actually continue to see overlayColor is internal, not public.

**Comment by gordontucker** [comment]
Sorry about that. I'm pushing 1.1.2 with it _actually_ public this time
