### ISSUE TITLE
Option to disable drag with fixed instrinsic height for sheet.

### ISSUE THREAD

**Issue by amberkatyal** [gordontucker/FittedSheets#71]
Hi,
The sheet works fine although I like an option to disable drag to change its height to full screen. I think it may work if I pass the size explicitly referring the code. But that might be difficult as I want it to be intrinsic size which won't be calculated at the time of init method.
I want the dismiss to drag or drag when making view small but should not increase the height. Is there any property to disable this functionality.

Thanks

**Comment by gordontucker** [comment]
I think I get what you are saying. I'm going to try and address this in the next major version I'm working on.
