### ISSUE TITLE
pullBarView is nil initially, resulting in a crash upon accessing before presenting

### ISSUE THREAD

**Issue by hipwelljo** [gordontucker/FittedSheets#8]
I would like to hide the pullBarView. I tried
```
let sheetController = SheetViewController(controller: viewController)
sheetController.pullBarView.isHidden = true
```
but this results in a fatal error, because pullBarView is an implicitly unwrapped optional yet it is `nil` until `setUpPullBarView()` is triggered. To address the issue, it could be defined 
`public private(set) weak var pullBarView = UIView() `
instead of
`public private(set) weak var pullBarView: UIView!`

Another option would be to perform the setup upon init instead of waiting until viewDidLoad.

I suspect this will be the same for the containerView as it's defined the same way.

**Comment by gordontucker** [comment]
I'll take a look at adding a better way to hide the pullBarView. I'm open to accepting a pull request if you want to make this change for me 😁
