### ISSUE TITLE
Blank Transparent page show when using default settings

### ISSUE THREAD

**Issue by yeeket** [gordontucker/FittedSheets#81]
I followed the default setting provided in the guide but it didnt show the VC instead show a transaparent page instead
Code is

import FittedSheets

        let controller = LoginViewController()

        let sheetController = SheetViewController(controller: controller)

        // It is important to set animated to false or it behaves weird currently
        self.present(sheetController, animated: false, completion: nil)
Did i do something wrong here ?

![Screenshot 2020-07-28 at 2 18 00 PM](https://user-images.githubusercontent.com/40782536/88626468-3f812700-d0dd-11ea-886f-13a57ce05c8a.png)

**Comment by gordontucker** [comment]
This is likely related to intrinsic heights. Try again with the 2.0.0 release and let me know if it is still happening.
