### ISSUE TITLE
how can I set the screen in to full screen?

### ISSUE THREAD

**Issue by jesuasir007** [gordontucker/FittedSheets#82]
currently I have set the screen into full ,but it's show the blank dark space in top ,how to remove drag bar and I have drag into full screen ,how to show the alert you reach max height ,please give me a solution, and hoe to remove the pull bar and leading spaces ....

**Comment by gordontucker** [comment]
This wasn't supported until the 2.0.0 release. Update and it should be an option now.

**Comment by jesuasir007** [comment]
Ok thank you
