### ISSUE TITLE
Question: How do i stop the main controller from zooming out

### ISSUE THREAD

**Issue by mathemandy** [gordontucker/FittedSheets#86]
When i present the sheet, the rootview tends to zoom in which i think is by default. 
i would like to present the modal without shrinking/zooming the rootview. 

I tried to use inlineMode = true. 

the view didnt appear as i couldnt get access to the `Constraint` class.

**Comment by Michael-Maher** [comment]
@mathemandy  
Just add this option in SheetOptions instance:
`                shrinkPresentingViewController: false
`
Then it works as you want now

**Comment by gordontucker** [comment]
@Michael-Maher is correct, `shrinkPresentingViewController` is the way to go. If you set that false it will no longer shrink the presenting view controller.
