### ISSUE TITLE
Ability to tap grip pull bar to dismiss (accessibility)

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [gordontucker/FittedSheets#88]
1.x included the ability to tap the pull bar grabber to dismiss, which was exposed to VoiceOver as I believe the only way to dismiss the sheet. It appears this is not possible in 2.0, I can't get it to dismiss with VoiceOver enabled.

**Comment by gordontucker** [comment]
This has been fixed in 2.0.6
