### ISSUE TITLE
Size to fit view controller view contents?

### ISSUE THREAD

**Issue by hipwelljo** [gordontucker/FittedSheets#9]
I initially thought the sheet was a fixed height, rather than determined by the size of the provided view controller's view, but I now see it is in fact determined by that intrinsic content size. Great! So this is a non-issue, except maybe that behavior should be noted in the readme so people can better understand what they can expect this library to do. :)

**Comment by gordontucker** [comment]
Maybe I should add a flag to let the user define this behavior... 🤔 
I'll update the readme to include this

**Comment by huylv-teko** [comment]
Hey try not to pass sizes in SheetViewControler constructor but it still not fit content, my content contains a talbeview, did i miss something or any flag to make it fit?

**Comment by fukemy** [comment]
@huylv-teko did u solved your problem, i meet same issue with tableviewcontroller
