### ISSUE TITLE
Sheet doesn't appear the next time you present it after swiping it down

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [gordontucker/FittedSheets#90]
If you present a sheet, swipe it down to dismiss, then present that same sheet (rather than create a new instance), it won't be visible. But if you tap outside to dismiss it instead of swipe to dismiss, presenting it again works.
[Screen Recording 2020-08-12 at 9.54.22 AM.zip](https://github.com/gordontucker/FittedSheets/files/5063970/Screen.Recording.2020-08-12.at.9.54.22.AM.zip)

Here I modified the IntrensicAndFullscreenDemo:

```
class IntrensicAndFullscreenDemo: Demoable {
    var sheet: SheetViewController?
    
    var name: String {
        return "Intrensic And Fullscreen"
    }
    
    func buildDemo(useInlineMode: Bool) -> SheetViewController {
        let controller = IntrinsicExampleViewController.instantiate()
        let options = SheetOptions(
            useFullScreenMode: false,
            useInlineMode: useInlineMode,
            minimumSpaceAbovePullBar: 44)
        if sheet == nil {
            sheet = SheetViewController(controller: controller, sizes: [.fullscreen], options: options)
        }
        return sheet!
    }
}
```

**Comment by gordontucker** [comment]
This has been fixed in 2.0.7
