### ISSUE TITLE
Change initial height of sheet

### ISSUE THREAD

**Issue by Michael-Maher** [gordontucker/FittedSheets#91]
As usual sheet controller starts from first height in sizes array, but what if i want to show sheet from another position not the first of the array. Ex:

sizes = [.percent(0.2), .percent(0.5), .percent(0.9)]

but i want to show sheet with initial  height  .percent(0.5) NOT .percent(0.2) so user can scroll up or scroll down as he want

**Comment by gordontucker** [comment]
Set sizes to [.percent(0.5), .percent(0.2), .percent(0.9)]. Internally it sorts them by the size, but the first one in the list you send is the initial, regardless of the position once sorted.

**Comment by Michael-Maher** [comment]
@gordontucker Yes i works fine in normal sheet mode but i want this scenario for inline mode
I tried [.percent(0.5), .percent(0.2), .percent(0.9)] but it doesn't work correctly.
Sheet initially starts with .percent(0.5)
then i can scroll only to .percent(0.9)

**Comment by gordontucker** [comment]
That does appear to be a bug. I'll look into it.

**Comment by gordontucker** [comment]
This is fixed in build 2.0.10.
