### ISSUE TITLE
Blur background

### ISSUE THREAD

**Issue by farhad01** [gordontucker/FittedSheets#92]
It would be good if there was a property to blur background.

**Comment by farhad01** [comment]
here is corresponding pr:
https://github.com/gordontucker/FittedSheets/pull/93

**Comment by gordontucker** [comment]
This has been integrated with 2.0.9 (I slightly modified your implementation, but it the contract is the same as you had it)

**Comment by farhad01** [comment]
Thanks for your effort, the way you implemented is much better the fadeout on dismissing will be handled this way too.
