### ISSUE TITLE
Retain cycle: presenting view controller does not deinit if sheet is stored in variable

### ISSUE THREAD

**Issue by jordanhbuiltbyhq** [gordontucker/FittedSheets#94]
If you store the sheet view controller in a variable to be able to present it again later, a retain cycle is introduced and thus the view controller is not deallocated when it should. I've created a little demo project where the root view controller presents a native sheet, the native sheet presents a fitted sheet, and when you dismiss the sheets the native sheet is not deallocated. Note that if you create and store the sheet view controller but don't present it, then dismissing the native sheet will deinit.

To reproduce:
1. Tap Present
2. Tap Present Sheet
3. Swipe to dismiss the fitted sheet
4. Swipe to dismiss the native sheet
Result: DEINIT was not logged to console

[SheetTest.zip](https://github.com/gordontucker/FittedSheets/files/5069879/SheetTest.zip)

**Comment by gordontucker** [comment]
This should be fixed in 2.0.8
