### ISSUE TITLE
PullBar Color

### ISSUE THREAD

**Issue by doyeka** [gordontucker/FittedSheets#96]
You should make it possible to customize the color of the pull bar. It would be an easy option to add vs. always making it clear, and it'd go a long way!!

https://user-images.githubusercontent.com/23086057/90323888-2fff3c00-df2d-11ea-8c7e-3a04913fe60e.png

**Comment by gordontucker** [comment]
This is implemented in 2.0.12 now. Thank you for the suggestion.
