### ISSUE TITLE
Pod Install and Update Issue

### ISSUE THREAD

**Issue by mirza4jobs** [gordontucker/FittedSheets#97]
Hi Guys,
I am trying to install Fittedsheets from Pod but I am seeing an older version of FittedSheets (1.4.6) 
I also tried specifying the release version  2.0.0 but shows error.

<img width="856" alt="Screen Shot 2020-08-17 at 2 17 28 PM" src="https://user-images.githubusercontent.com/23484769/90429949-99e62580-e094-11ea-84cd-fde9218af00f.png">

Thank you
Regards,
Mirza

**Comment by gordontucker** [comment]
The current minimum requirement deployment target for FittedSheets is iOS 11, and it looks like you may have an older version targeted.

**Comment by mirza4jobs** [comment]
Thanks for the clarification 🙏
Regards,
Mirza
