### ISSUE TITLE
SPM Install and Update Issue

### ISSUE THREAD

**Issue by furiosFast** [gordontucker/FittedSheets#98]
Hi, 
i've update now the library to the last version (2.1.1), but now my application does not compile!
There are 7 errors inside FittedSheets, everyone like this: "'safeAreaInsets' is only available in iOS 11.0 or newer".

i've see inside Package.swift this lines:
```
platforms: [
    .iOS(.v10), .tvOS(.v10), .macOS(.v10_12), .watchOS(.v3)
],
```

thank you

**Comment by gordontucker** [comment]
The latest version only supports iOS 11, so I've updated the package to reflect that, sorry I missed the package file. I'm not opposed to supporting older versions if you need them, I just don't have the time right now to test against them.

**Comment by furiosFast** [comment]
ok thank you

**Comment by fukemy** [comment]
same problem, here is example, too many errors 
![Uploading Screen Shot 2020-10-06 at 21.41.54.png…]()
